# Generated by Django 5.2.1 on 2025-05-29 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='frequencia',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='periodicidade',
            field=models.CharField(blank=True, choices=[('nenhuma', 'Nenhuma'), ('diaria', 'Diariamente'), ('semanal', 'Semanalmente'), ('mensal', 'Mensalmente')], default='nenhuma', max_length=10, null=True),
        ),
    ]
