# Generated by Django 5.2.1 on 2025-05-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_evento_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='frequencia',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='evento',
            name='periodicidade',
            field=models.CharField(choices=[('nenhuma', 'Nenhuma'), ('diaria', 'Diariamente'), ('semanal', 'Semanalmente'), ('mensal', 'Mensalmente')], default='nenhuma', max_length=10),
        ),
    ]
